sudo: required

services:
  - docker

notifications:
  email: false

before_script:
  - docker pull dalg24/cap-stack

script:
  - docker build -t dalg24/cap .

after_success:
  - docker login -e="${DOCKER_EMAIL}" -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
  - docker push dalg24/cap
