sudo: required

language: cpp

services:
  - docker

notifications:
  email: false

before_install:
  - docker pull dalg24/cap-stack
  - docker build -t dalg24/cap .
before_script:
script:
  - ctest -V
