sudo: required

language: cpp

services:
  - docker

notifications:
  email: false

before_install:
  - docker pull dalg24/cap-stack
before_script:
script:
  - docker build -t dalg24/cap .
after_success:
  - docker push dalg24/cap
