sudo: required

services:
  - docker

notifications:
  email: false

before_script:
  - docker pull dalg24/cap-stack

script:
  - docker --version
  - pwd
  - docker run
        -e CI=true
        -e TRAVIS=true
        -e TRAVIS_BRANCH=${TRAVIS_BRANCH}
        -e TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER}
        -e TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID}
        -e TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
        -e TRAVIS_COMMIT=${TRAVIS_COMMIT}
        -e TRAVIS_BUILD_DIR=/scratch/source/cap
        -v ${PWD}:/scratch/source/cap
        dalg24/cap-stack
        /scratch/source/cap/docker/build_cap.sh
