sudo: required

services:
  - docker

notifications:
  email: false

before_script:
  - docker pull dalg24/cap-stack

script:
  - docker --version
  - pwd
  - docker run -v ${PWD}:/scratch/source/cap dalg24/cap-stack /scratch/source/cap/docker/build_cap.sh
