sudo: required

services:
  - docker

notifications:
  email: false

language: python

cache: pip

before_install:
  - docker pull dalg24/cap-stack
  - docker run
        --detach --tty
        --name=test-machine
        --volume ${TRAVIS_BUILD_DIR}:/scratch/source/cap
        --env TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}
        --env CTEST_BUILD_NAME="$(./docker/get_build_info.sh)"
        dalg24/cap-stack
  - docker exec test-machine
        sh -xe /scratch/source/cap/docker/build_cap.sh
  - docker cp test-machine:/scratch/build/cap/lcov.info .
  - docker cp test-machine:/scratch/build/cap/coverage.xml .

install:
  - pip install -q codecov

script:
  - echo "Hello World"

after_success:
  - codecov
        --disable gcov search pycov
        --file lcov.info coverage.xml
