notifications:
  email: false

language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-all-dev
install:
  - python --version
  - cmake
  - make
before_script:
script:
  - ctest
