sudo: required

services:
  - docker

notifications:
  email: false

before_install:
  - pip install codecov
  - docker pull dalg24/cap-stack

script:
  - docker --version
  - pwd
  - docker run
        -v ${TRAVIS_BUILD_DIR}:/scratch/source/cap
        dalg24/cap-stack
        /scratch/source/cap/docker/build_cap.sh

after_success:
  - codecov
        --disable gcov search pycov
        --file lcov.info coverage.xml
